module.exports = {
  "amputa": 1,
  "animal ka": 1,
  "binibrocha": 1,
  "bobo": 1,
  "brocha": 1,
  "burat": 1,
  "bwesit": 1,
  "bwisit": 1,
  "engot": 1,
  "gaga": 1,
  "gagi": 1,
  "gago": 1,
  "hayop ka": 1,
  "hayup": 1,
  "hinayupak": 1,
  "hudas": 1,
  "inutel": 1,
  "inutil": 1,
  "kagaguhan": 1,
  "kantot": 1,
  "kantotan": 1,
  "kantut": 1,
  "kantutan": 1,
  "kaululan": 1,
  "kiki": 1,
  "kingina": 1,
  "kupal": 1,
  "leche": 1,
  "lechugas": 1,
  "lintik": 1,
  "nakakaburat": 1,
  "nimal": 1,
  "ogag": 1,
  "pakingshet": 1,
  "pakshet": 1,
  "pakyu": 1,
  "pesteng yawa": 1,
  "poke": 1,
  "poki": 1,
  "pokpok": 1,
  "poyet": 1,
  "pu'keng": 1,
  "pucha": 1,
  "puchanggala": 1,
  "puchangina": 1,
  "puke": 1,
  "puki": 1,
  "puking": 1,
  "punyeta": 1,
  "puta": 1,
  "putang": 1,
  "putang ina": 1,
  "putangina": 1,
  "putanginamo": 1,
  "puyet": 1,
  "ratbu": 1,
  "shunga": 1,
  "sira ulo": 1,
  "siraulo": 1,
  "susu": 1,
  "tae": 1,
  "taena": 1,
  "tamod": 1,
  "tanga": 1,
  "tangina": 1,
  "tarantado": 1,
  "tete": 1,
  "teti": 1,
  "tingil": 1,
  "tite": 1,
  "titi": 1,
  "ulol": 1,
  "ungas": 1,
  "lolo": 1,
  "bilat": 1,
  "kayat": 1,
  "leching ina": 1,
  "hinampak": 1,
  "anak sa pobring olok": 1,
  "bilat sa kagang": 1,
  "bilat bilat": 1,
  "bogo kag mama": 1,
  "bogo": 1
};